version: '3.3'
services:
    adguardhome:
        container_name: adguardhome
        restart: unless-stopped
        volumes:
            - './work:/opt/adguardhome/work'
            - './config:/opt/adguardhome/conf'
        ports:
            - '53:53/tcp'
            - '53:53/udp'
            - '67:67/udp'
            - '68:68/tcp'
            - '68:68/udp'
            - '7676:80/tcp'
            - '7878:443/tcp'
            - '7878:443/udp'
        image: adguard/adguardhome
