services:
    web:
        image: daledavies/jump
        restart: unless-stopped
        ports:
            - 7070:8080
        volumes:
            - ./backgrounds:/backgrounds
            - ./favicon:/favicon
            - ./search:/search
            - ./sites:/sites
        environment:
            SITENAME: 'CyberArcher'
            SHOWCLOCK: 'false'
            CHECKSTATUS: 'false'
            SHOWSEARCH: 'false'
            LATLONG: '51.509865,-0.118092'
            OWMAPIKEY: '0a1b2c3d4e5f6a7b8c9d0a1b'
            BGBLUR: 20
            CUSTOMGREETING: 'Hello, DXC-0 :)'
