version: '3.9'

services:
  ntp:
    build: .
    image: cturra/ntp:latest
    container_name: ntp
    restart: always
    ports:
      - 123:123/udp
    environment:
      - NTP_SERVERS=ntp.laas.fr, ntp.ensma.fr, ntp.polytechnique.fr
      - LOG_LEVEL=0
      - TZ=Europe/Paris
